platform :ios, '15.0'
use_frameworks!

target 'App' do
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorStatusBar', :path => '../../node_modules/@capacitor/status-bar'
  # حزمة الإشعارات التي سبب المشكلة
  pod 'CapacitorPushNotifications', :path => '../../node_modules/@capacitor/push-notifications'
  
  # حزمة التخزين المحلية إن كانت مستخدمة
  pod 'CapacitorPreferences', :path => '../../node_modules/@capacitor/preferences'

  pod 'CapacitorFirebaseMessaging', :path => '../../node_modules/@capacitor-firebase/messaging'

  # مكتبات Firebase
  pod 'FirebaseCore'
  pod 'Firebase/Messaging'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end